root: true
env:
  browser: true
  es2021: true
settings:
  react:
    version: "detect"
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
rules:
  react/react-in-jsx-scope: off
  prettier/prettier: warn
  semi:
    - error
    - always
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var: error
  indent:
    - error
    - 2
  max-len:
    - warn
    - 120
